version: "3.4"

x-common-variables: &common-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

volumes:
  pg_sandbox_data:
  pg_development_data:

services:
  server:
    build: ./server
    image: plaidinc/pattern-server:1.0.7
    ports:
      - 5001:5001
    environment:
      <<: *common-variables
      PLAID_CLIENT_ID:
      PLAID_SECRET_SANDBOX:
      PLAID_SECRET_DEVELOPMENT:
      PLAID_SANDBOX_REDIRECT_URI:
      PLAID_DEVELOPMENT_REDIRECT_URI:
      PLAID_ENV:
      PORT: 5001
      DB_PORT: 5432
      DB_HOST_NAME: db
    depends_on:
      - db

  client:
    build: ./client
    image: plaidinc/pattern-client:1.0.7
    ports:
      - 3001:3001
    environment:
      REACT_APP_PLAID_ENV: ${PLAID_ENV}
      REACT_APP_SERVER_HOST: http://localhost:5001
    depends_on:
      - server
